version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - automation
      - dependencies
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - automation
      - dependencies
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    cooldown:
      default-days: 10

  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: nixpkgs
    labels:
      - automation
      - dependencies
    groups:
      nixpkgs:
        patterns:
          - nixpkgs
