/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as BlogRouteImport } from './routes/_blog/route'
import { Route as IndexImport } from './routes/index'
import { Route as AboutIndexImport } from './routes/about.index'
import { Route as AboutLangImport } from './routes/about.$lang'
import { Route as BlogArchiveRouteImport } from './routes/_blog/_archive.route'
import { Route as BlogPostSlugImport } from './routes/_blog/post.$slug'
import { Route as BlogArchivePostIndexImport } from './routes/_blog/_archive.post.index'
import { Route as BlogArchiveCategoryIndexImport } from './routes/_blog/_archive.category.index'
import { Route as BlogArchiveCategorySlugImport } from './routes/_blog/_archive.category.$slug'

// Create/Update Routes

const BlogRouteRoute = BlogRouteImport.update({
  id: '/_blog',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const AboutLangRoute = AboutLangImport.update({
  id: '/about/$lang',
  path: '/about/$lang',
  getParentRoute: () => rootRoute,
} as any)

const BlogArchiveRouteRoute = BlogArchiveRouteImport.update({
  id: '/_archive',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogPostSlugRoute = BlogPostSlugImport.update({
  id: '/post/$slug',
  path: '/post/$slug',
  getParentRoute: () => BlogRouteRoute,
} as any)

const BlogArchivePostIndexRoute = BlogArchivePostIndexImport.update({
  id: '/post/',
  path: '/post/',
  getParentRoute: () => BlogArchiveRouteRoute,
} as any)

const BlogArchiveCategoryIndexRoute = BlogArchiveCategoryIndexImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => BlogArchiveRouteRoute,
} as any)

const BlogArchiveCategorySlugRoute = BlogArchiveCategorySlugImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => BlogArchiveRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_blog': {
      id: '/_blog'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRoute
    }
    '/_blog/_archive': {
      id: '/_blog/_archive'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof BlogArchiveRouteImport
      parentRoute: typeof BlogRouteImport
    }
    '/about/$lang': {
      id: '/about/$lang'
      path: '/about/$lang'
      fullPath: '/about/$lang'
      preLoaderRoute: typeof AboutLangImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/_blog/post/$slug': {
      id: '/_blog/post/$slug'
      path: '/post/$slug'
      fullPath: '/post/$slug'
      preLoaderRoute: typeof BlogPostSlugImport
      parentRoute: typeof BlogRouteImport
    }
    '/_blog/_archive/category/$slug': {
      id: '/_blog/_archive/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof BlogArchiveCategorySlugImport
      parentRoute: typeof BlogArchiveRouteImport
    }
    '/_blog/_archive/category/': {
      id: '/_blog/_archive/category/'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof BlogArchiveCategoryIndexImport
      parentRoute: typeof BlogArchiveRouteImport
    }
    '/_blog/_archive/post/': {
      id: '/_blog/_archive/post/'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof BlogArchivePostIndexImport
      parentRoute: typeof BlogArchiveRouteImport
    }
  }
}

// Create and export the route tree

interface BlogArchiveRouteRouteChildren {
  BlogArchiveCategorySlugRoute: typeof BlogArchiveCategorySlugRoute
  BlogArchiveCategoryIndexRoute: typeof BlogArchiveCategoryIndexRoute
  BlogArchivePostIndexRoute: typeof BlogArchivePostIndexRoute
}

const BlogArchiveRouteRouteChildren: BlogArchiveRouteRouteChildren = {
  BlogArchiveCategorySlugRoute: BlogArchiveCategorySlugRoute,
  BlogArchiveCategoryIndexRoute: BlogArchiveCategoryIndexRoute,
  BlogArchivePostIndexRoute: BlogArchivePostIndexRoute,
}

const BlogArchiveRouteRouteWithChildren =
  BlogArchiveRouteRoute._addFileChildren(BlogArchiveRouteRouteChildren)

interface BlogRouteRouteChildren {
  BlogArchiveRouteRoute: typeof BlogArchiveRouteRouteWithChildren
  BlogPostSlugRoute: typeof BlogPostSlugRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogArchiveRouteRoute: BlogArchiveRouteRouteWithChildren,
  BlogPostSlugRoute: BlogPostSlugRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof BlogArchiveRouteRouteWithChildren
  '/about/$lang': typeof AboutLangRoute
  '/about': typeof AboutIndexRoute
  '/post/$slug': typeof BlogPostSlugRoute
  '/category/$slug': typeof BlogArchiveCategorySlugRoute
  '/category': typeof BlogArchiveCategoryIndexRoute
  '/post': typeof BlogArchivePostIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof BlogArchiveRouteRouteWithChildren
  '/about/$lang': typeof AboutLangRoute
  '/about': typeof AboutIndexRoute
  '/post/$slug': typeof BlogPostSlugRoute
  '/category/$slug': typeof BlogArchiveCategorySlugRoute
  '/category': typeof BlogArchiveCategoryIndexRoute
  '/post': typeof BlogArchivePostIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_blog': typeof BlogRouteRouteWithChildren
  '/_blog/_archive': typeof BlogArchiveRouteRouteWithChildren
  '/about/$lang': typeof AboutLangRoute
  '/about/': typeof AboutIndexRoute
  '/_blog/post/$slug': typeof BlogPostSlugRoute
  '/_blog/_archive/category/$slug': typeof BlogArchiveCategorySlugRoute
  '/_blog/_archive/category/': typeof BlogArchiveCategoryIndexRoute
  '/_blog/_archive/post/': typeof BlogArchivePostIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about/$lang'
    | '/about'
    | '/post/$slug'
    | '/category/$slug'
    | '/category'
    | '/post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about/$lang'
    | '/about'
    | '/post/$slug'
    | '/category/$slug'
    | '/category'
    | '/post'
  id:
    | '__root__'
    | '/'
    | '/_blog'
    | '/_blog/_archive'
    | '/about/$lang'
    | '/about/'
    | '/_blog/post/$slug'
    | '/_blog/_archive/category/$slug'
    | '/_blog/_archive/category/'
    | '/_blog/_archive/post/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  AboutLangRoute: typeof AboutLangRoute
  AboutIndexRoute: typeof AboutIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  AboutLangRoute: AboutLangRoute,
  AboutIndexRoute: AboutIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_blog",
        "/about/$lang",
        "/about/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_blog": {
      "filePath": "_blog/route.tsx",
      "children": [
        "/_blog/_archive",
        "/_blog/post/$slug"
      ]
    },
    "/_blog/_archive": {
      "filePath": "_blog/_archive.route.tsx",
      "parent": "/_blog",
      "children": [
        "/_blog/_archive/category/$slug",
        "/_blog/_archive/category/",
        "/_blog/_archive/post/"
      ]
    },
    "/about/$lang": {
      "filePath": "about.$lang.tsx"
    },
    "/about/": {
      "filePath": "about.index.tsx"
    },
    "/_blog/post/$slug": {
      "filePath": "_blog/post.$slug.tsx",
      "parent": "/_blog"
    },
    "/_blog/_archive/category/$slug": {
      "filePath": "_blog/_archive.category.$slug.tsx",
      "parent": "/_blog/_archive"
    },
    "/_blog/_archive/category/": {
      "filePath": "_blog/_archive.category.index.tsx",
      "parent": "/_blog/_archive"
    },
    "/_blog/_archive/post/": {
      "filePath": "_blog/_archive.post.index.tsx",
      "parent": "/_blog/_archive"
    }
  }
}
ROUTE_MANIFEST_END */
