name: Feed test

on:
  workflow_dispatch:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-feed:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Nix
        uses: ./.github/actions/setup
        with:
          cache-key: feed-test

      - name: Run feed test
        run: nix develop -L .#node-build -c pnpm run test:http:feed
